version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - etc
  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile
    ports: 
      - '8000:8000'
    stdin_open: true
    tty: true
    depends_on: 
      - backend
    networks:
      - etc
networks:
  etc:
    driver: bridge