version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - etc
  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on: 
      - api
    networks:
      - etc
networks:
  etc:
    driver: bridge