version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  spa:
    build: ./spa
    ports: 
      - '8000:8000'
    volumes: 
      - ./spa/src:/app/src
    stdin_open: true
    tty: true
    depends_on: 
      - backend
